#!/bin/bash

PHASE=$( echo ${1} | awk '{ print tolower($0); }' )
if [[ "${PHASE}" == "" ]]; then
    echo "missing phase!"
    exit 1
fi
if [[ "${PHASE}" != "stg" && "${PHASE}" != "prd"  ]]; then
    echo "invalid phase!"
    exit 1
fi

SCRIPT_DIR=$( dirname $0 )
echo "~> ${SCRIPT_DIR}/goose.sh ${PHASE}"
${SCRIPT_DIR}/goose.sh ${PHASE}

echo "~> sudo systemctl daemon-reload"
sudo systemctl daemon-reload

echo "~> sudo systemctl stop amnezic.be.${PHASE}.service"
sudo systemctl stop amnezic.be.${PHASE}.service

echo "~> sudo systemctl start amnezic.be.${PHASE}.service"
sudo systemctl start amnezic.be.${PHASE}.service

echo "~> sudo systemctl status amnezic.be.${PHASE}.service"
sudo systemctl status amnezic.be.${PHASE}.service
